book/urls.py
"""
Url Patterns for Book App
"""
from django.urls import path

from book import views

urlpatterns = [
    path('', views.BooksListView.as_view(),
         name='index'),
    path('<int:pk>', views.BookDetailView.as_view(),
         name='book-details'),
    path('<int:pk>/delete', views.BookDeleteView.as_view(),
         name='book-delete'),
    path('<int:pk>/update', views.BookUpdateView.as_view(),
         name='book-update')
]

comment/urls.py
"""
Urls for Comment App
"""
from django.urls import path
from comment import views

urlpatterns = [
    path('<int:pk>/review/add', views.ReviewCreateView.as_view(), name='review-add'),
    path('review/<int:pk>', views.ReviewDetailView.as_view(), name='review-details'),
    path('review/<int:pk>/update', views.ReviewUpdateView.as_view(), name='review-update'),
    path('review/<int:pk>/delete', views.ReviewDeleteView.as_view(), name='review-delete'),
    path('review/<int:pk>/comment/add/<reply_to>', views.CommentCreateView.as_view(), name='comment-add'),
    path('<int:pk>/update', views.CommentUpdateView.as_view(), name='comment-update'),
    path('<int:pk>/delete', views.CommentDeleteView.as_view(), name='comment-delete'),
]

django_books/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from book.views import index
from user.api import GetToken, RetrieveUser

urlpatterns = [
                  path('', index),
                  path('book/',
                       include(('book.urls', 'book'), namespace='book')),
                  path('accounts/',
                       include(('user.urls', 'user'), namespace='user')),
                  path('comment/', include(('comment.urls', 'comment'),
                                           namespace='comment')),
                  path('api/author/', include('author.urls')),
                  path('api/book/', include('book.api')),
                  path('api/user/<int:pk>', RetrieveUser.as_view()),
                  path('api/login/', GetToken.as_view()),
                  path('api-login/', include('rest_framework.urls')),
                  path('admin/', admin.site.urls, name='admin'),
                  path('__debug__/', include(debug_toolbar.urls)),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'error_handlers.views.handler403'
handler404 = 'error_handlers.views.handler404'
handler500 = 'error_handlers.views.handler500'

softserve_demo1_books/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from book.views import index
from user.api import GetToken, RetrieveUser

urlpatterns = [
                  path('', index),
                  path('book/',
                       include(('book.urls', 'book'), namespace='book')),
                  path('accounts/',
                       include(('user.urls', 'user'), namespace='user')),
                  path('comment/', include(('comment.urls', 'comment'),
                                           namespace='comment')),
                  path('api/author/', include('author.urls')),
                  path('api/book/', include('book.api')),
                  path('api/user/<int:pk>', RetrieveUser.as_view()),
                  path('api/login/', GetToken.as_view()),
                  path('api-login/', include('rest_framework.urls')),
                  path('admin/', admin.site.urls, name='admin'),
                  path('__debug__/', include(debug_toolbar.urls)),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'error_handlers.views.handler403'
handler404 = 'error_handlers.views.handler404'
handler500 = 'error_handlers.views.handler500'

comment/models.py
from typing import Tuple

from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db import models
from django.db.models import QuerySet


class Review(models.Model):
    """
    Review Model
    """

    RATING_CHOICES = zip(range(1, 6), range(1, 6))

    reviewer = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    book = models.ForeignKey('book.Book', on_delete=models.CASCADE)

    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.IntegerField(choices=RATING_CHOICES)

    approved = models.BooleanField(default=False)

    def __repr__(self) -> str:
        """
        Repr method overriding
        :return: str
        """
        return self.reviewer.username + ' : ' + self.book.title

    def __str__(self) -> str:
        """
        Str method overriding
        :return: str
        """
        return self.title

    @property
    def intro(self) -> str:
        """
        Review Intro displayed in Book Details View
        :return: str
        """
        return self.text[:100] + '...'

    @property
    def owner(self) -> User:
        """
        Property for accessing the user who wrote the review.
        Added for compatibility with Comment model.
        :return: User
        """
        return self.reviewer

    def save(self, *args, **kwargs):
        """
        All comments written by superuser or moderator are approved by default
        """
        if self.reviewer.is_superuser or self.reviewer.groups.filter(
                name='moderator').exists():
            self.approved = True
        super().save(*args, **kwargs)

    @classmethod
    def get_book_reviews(cls, *, pk: int, page: int = 0,
                         paginate_by: int = 12) -> Tuple[QuerySet, Paginator]:
        """
        Return Book Reviews and Pagination object.
        Used in Book Details view.
        :param pk: int
        :param page: int = 0
        :param paginate_by: int = 12
        :return: Tuple[QuerySet, Paginator]
        """
        pag = Paginator(
            cls.objects.select_related('reviewer').filter(approved=True,
                                                          book__pk=pk),
            paginate_by)
        return pag.page(page).object_list, pag


class Comment(models.Model):
    """
    Comment Model
    """

    writer = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    review = models.ForeignKey('comment.Review', on_delete=models.CASCADE)
    replied_to = models.ForeignKey('comment.Comment', on_delete=models.CASCADE,
                                   null=True, blank=True, default=None)
    text = models.CharField(max_length=1024)
    approved = models.BooleanField(default=False)

    @property
    def owner(self) -> User:
        """
        Property for accessing the user who wrote the review.
        Added for compatibility with Review model.
        :return: User
        """
        return self.writer

    def __repr__(self) -> str:
        """
        Repr method overriding
        :return: str
        """
        return self.writer.username + " : " + str(self.review.pk)

    def __str__(self) -> str:
        """
        Str method overriding
        :return: str
        """
        return self.text[:100]

    def save(self, *args, **kwargs):
        """
        All comments written by superuser or moderator are approved by default
        """
        if self.writer.is_superuser or self.writer.groups.filter(
                name='moderator').exists():
            self.approved = True
        super().save(*args, **kwargs)

    @classmethod
    def get_review_comments(cls, *, pk: int, page: int = 0,
                            paginate_by: int = 12) \
            -> Tuple[QuerySet, Paginator]:
        """
        Return Review Comments and Pagination object.
        Used in Book Reviews view.
        :param pk: int
        :param page: int = 0
        :param paginate_by: int = 12
        :return: Tuple[QuerySet, Paginator]
        """
        pag = Paginator(cls.objects.prefetch_related('writer')
                        .filter(approved=True, review__pk=pk), paginate_by)
        return pag.page(page).object_list, pag

comment/forms.py
from django.forms import ModelForm
from django.forms.widgets import Textarea

from comment.models import Review, Comment


class ReviewForm(ModelForm):
    """
    Django Form for Review Model used when creating or updating Review objects
    """

    class Meta:
        model = Review
        fields = ('title', 'text', 'rating',)


class CommentForm(ModelForm):
    """
    Django Form for Comment Model used when creating or updating Comment objects
    """

    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {'text': Textarea}

comment/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views.generic import (CreateView, DetailView,
                                  UpdateView, DeleteView)

from comment.forms import ReviewForm, CommentForm
from comment.models import Review, Comment
from utils.user_utils import (OwnerOrModeratorRequiredMixin,
                              LoginRequiredMixin, current_user_is_moderator)


class ReviewCreateView(LoginRequiredMixin, CreateView):
    """
    Create Review
    """
    model = Review
    form_class = ReviewForm
    template_name = 'comment/review_form.html'

    def get_context_data(self, **kwargs):
        """
        Insert submit url and submit button text into template context.
        Needed because we use the same template for
        updating and creating reviews.
        """
        context = super().get_context_data(**kwargs)
        context['submit_url'] = reverse_lazy('comment:review-add',
                                             kwargs={
                                                 'pk': self.kwargs.get('pk')
                                             })
        context['submit_text'] = 'Add Review'
        return context

    def form_valid(self, form):
        """
        Add Book id and Reviewer id fields to object before saving it.
        """
        review = Review(title=form.cleaned_data['title'],
                        text=form.cleaned_data['text'],
                        rating=form.cleaned_data['rating'])
        review.book_id = self.kwargs.get('pk')
        review.reviewer_id = self.request.user.pk
        review.save()
        return HttpResponseRedirect(reverse('book:book-details',
                                            kwargs={
                                                'pk': self.kwargs.get('pk')
                                            }))


class ReviewDetailView(DetailView):
    """
    Review Details
    """
    model = Review
    paginate_by = 12
    context_object_name = 'review'
    template_name = 'comment/review_detail.html'

    def get_queryset(self):
        """
        Select Related Book for better performance
        """
        return super().get_queryset().select_related('book')

    def get_context_data(self, **kwargs):
        """
        Insert page number and comments into template context
        """
        context = super().get_context_data(**kwargs)
        page = self.request.GET.get('page') or 1
        context['comments'], context['page_obj'] = Comment.get_review_comments(
            pk=self.object.pk,
            page=page,
            paginate_by=self.paginate_by
        )
        context['current_user_is_moderator'] = \
            current_user_is_moderator(self.request)
        return context


class ReviewUpdateView(OwnerOrModeratorRequiredMixin, UpdateView):
    """
    Review Update
    """
    model = Review
    form_class = ReviewForm
    template_name = 'comment/review_form.html'

    def get_context_data(self, **kwargs):
        """
        Insert submit url and submit button text into template context.
        Needed because we use the same template
        for updating and creating reviews.
        """
        context = super().get_context_data(**kwargs)
        context['submit_url'] = reverse_lazy('comment:review-update',
                                             kwargs={
                                                 'pk': self.kwargs.get('pk')
                                             })
        context['submit_text'] = 'Update Review'
        return context

    def get_success_url(self):
        """
        Return User to Review Details page
        """
        return reverse_lazy('comment:review-details', kwargs={
            'pk': self.kwargs.get('pk')
        })


class ReviewDeleteView(OwnerOrModeratorRequiredMixin, DeleteView):
    """
    Review Delete. Only available for superuser, moderator and review owner
    """
    model = Review

    def get_success_url(self):
        """
        Return User to Book Details Page
        """
        return reverse_lazy('book:book-details', kwargs={
            'pk': self.object.book_id
        })


class CommentCreateView(LoginRequiredMixin, CreateView):
    """
    Comment Create
    """
    model = Comment
    form_class = CommentForm
    template_name = 'comment/comment_form.html'

    def get_context_data(self, **kwargs):
        """
        Insert submit url and submit button text into template context.
        Needed because we use the same template
        for updating and creating comments.
        """
        context = super().get_context_data(**kwargs)
        context['submit_url'] = reverse_lazy('comment:comment-add', kwargs={
            'pk': self.kwargs.get('pk'),
            'reply_to': self.kwargs.get('reply_to')
        })
        context['submit_text'] = 'Add Comment'
        return context

    def form_valid(self, form):
        """
        Add Writer id and Reviewer id fields to object before saving it.
        """
        comment = Comment(text=form.cleaned_data['text'])
        comment.writer_id = self.request.user.pk
        comment.review_id = self.kwargs.get('pk')
        if self.kwargs.get('reply_to') != 'None':
            comment.replied_to_id = self.kwargs.get('reply_to')
        comment.save()
        return HttpResponseRedirect(reverse('comment:review-details',
                                            kwargs={
                                                'pk': self.kwargs.get('pk')
                                            }))


class CommentUpdateView(OwnerOrModeratorRequiredMixin, UpdateView):
    """
    Comment Update. Only available for superuser, moderator and review owner
    """
    model = Comment
    form_class = CommentForm
    template_name = 'comment/comment_form.html'

    def get_context_data(self, **kwargs):
        """
        Insert submit url and submit button text into template context.
        Needed because we use the same template
        for updating and creating comments.
        """
        context = super().get_context_data(**kwargs)
        context['submit_url'] = reverse_lazy('comment:comment-update', kwargs={
            'pk': self.kwargs.get('pk')
        })
        context['submit_text'] = 'Update Comment'
        return context

    def get_success_url(self):
        """
        Return User to Review Details Page
        """
        return reverse_lazy('comment:review-details', kwargs={
            'pk': self.object.review_id
        })


class CommentDeleteView(OwnerOrModeratorRequiredMixin, DeleteView):
    """
    Comment Delete. Only available for superuser, moderator and review owner
    """
    model = Comment
    context_object_name = 'comment'

    def get_success_url(self):
        """
        Return User to Review Details Page
        """
        return reverse_lazy('comment:review-details', kwargs={
            'pk': self.object.review_id
        })

comment/templates/comment/comment_branch.html
{% load comment_extras %}

<div class="d-flex flex-start mt-4">
    <img
        class="rounded-circle shadow-1-strong me-3"
        src="{{ comment.writer.profile_pic.url|default:'/media/profile_pics/default.png' }}"
        alt="avatar"
        width="65"
        height="65"
        />
    <div class="flex-grow-1 flex-shrink-1">
        <div>
            <div class="d-flex justify-content-between align-items-center">
                <p class="mb-1">
                    {{ comment.writer }}
                    {% if current_user_is_moderator or comment.writer.pk == current_user_pk %}
                    <a href="{% url 'comment:comment-update' pk=comment.pk %}"
                        ><i class="fas fa-reply fa-xs"></i
                        ><span class="small"> edit</span>
                    </a>
                    <a href="{% url 'comment:comment-delete' pk=comment.pk %}"
                        ><i class="fas fa-reply fa-xs"></i
                        ><span class="small"> delete</span>
                    </a>
                    {% endif %}
                </p>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'comment:comment-add' pk=review.pk reply_to=comment.pk %}"
                        ><i class="fas fa-reply fa-xs"></i
                        ><span class="small"> reply</span>
                    </a>
                {% endif %}
            </div>
            <p class="small mb-0">
                {{ comment.text }}
            </p>
        </div>
        {% for comment in comments|children:comment %}
        {% include "comment/comment_branch.html" with comments=comments comment=comment %}
        {% endfor %}
    </div>
</div>

comment/templates/comment/comment_confirm_delete.html
{% extends 'base.html' %}

{% block main %}
    <div class="container jumbotron" style="width: 70%; margin: 50px auto;">
        <form action="{% url 'comment:comment-delete' pk=comment.pk %}" method="POST">
            {% csrf_token %}
            <h3>Are you sure you want to delete this comment?</h3>
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
    </div>
{% endblock %}

comment/templates/comment/comment_form.html
{% extends 'base.html' %}

{% block main %}
    <div class="jumbotron" style="width: 70%; margin: 50px auto;">
        <form action="{{ submit_url }}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary" type="submit">{{ submit_text }}</button>
        </form>
    </div>
{% endblock %}

comment/templates/comment/review_detail.html
{% extends 'base.html' %} {% load comment_extras %} {% block main %}
<div id="review" class="jumbotron" style="width: 70%; margin: 50px auto;">
    <h2>{{ review.title }}</h2>
    <h5>written by {{ review.reviewer }}</h5>
    <h5>Book "{{ review.book }}" rated {{ review.rating }}</h5>

    <p>{{ review.text|safe }}</p>

    {% if current_user_is_moderator %}
    <div>
        <br />
        <h5>Moderator Buttons</h5>
        <a class="btn btn-secondary edit-button" href="{% url 'comment:review-update' pk=review.pk %}">Edit</a>
        <button class="btn btn-danger delete-button" data-bs-toggle="modal" data-bs-target="#deleteReviewModal">Delete</button>
    </div>
    {% endif %}
</div>

<div id="comments">
    <section id="comments">
        <div class="container my-5 py-5">
            <div class="row d-flex" style="justify-content: space-around;">
                <div class="col-md-12 col-lg-10 col-xl-8">
                    <div class="card">
                        <div class="card-body p-4">
                            <h4 class="text-center mb-4 pb-2">Comments</h4>

                            <div class="row">
                                <div class="col">
                                    {% with request.user.pk as current_user_pk %} {% for comment in comments|first_child %} {% include "comment/comment_branch.html" with comments=comments %} {% endfor %} {% endwith %}
                                </div>
                            </div>

                            {% if request.user.is_authenticated %}
                            <div class="container m-4">
                                <a href="{% url 'comment:comment-add' reply_to=None pk=review.pk  %}" class="btn btn-primary">Add Comment</a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

{% block modals %}
<div class="modal fade" id="deleteReviewModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete Review?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this review and everything associated with it?
            </div>
            <div class="modal-footer">
                <form action="{% url 'comment:review-delete' pk=review.pk %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %} {% endblock %}

comment/templates/comment/review_form.html
{% extends 'base.html' %}

{% block main %}
    <div class="jumbotron" style="width: 70%; margin: 50px auto;">
        <form action="{{ submit_url }}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary" type="submit">{{ submit_text }}</button>
        </form>
    </div>
{% endblock %}