book/urls.py
"""
Url Patterns for Book App
"""
from django.urls import path

from book import views

urlpatterns = [
    path('', views.BooksListView.as_view(),
         name='index'),
    path('<int:pk>', views.BookDetailView.as_view(),
         name='book-details'),
    path('<int:pk>/delete', views.BookDeleteView.as_view(),
         name='book-delete'),
    path('<int:pk>/update', views.BookUpdateView.as_view(),
         name='book-update')
]

django_books/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from book.views import index
from user.api import GetToken, RetrieveUser

urlpatterns = [
                  path('', index),
                  path('book/',
                       include(('book.urls', 'book'), namespace='book')),
                  path('accounts/',
                       include(('user.urls', 'user'), namespace='user')),
                  path('comment/', include(('comment.urls', 'comment'),
                                           namespace='comment')),
                  path('api/author/', include('author.urls')),
                  path('api/book/', include('book.api')),
                  path('api/user/<int:pk>', RetrieveUser.as_view()),
                  path('api/login/', GetToken.as_view()),
                  path('api-login/', include('rest_framework.urls')),
                  path('admin/', admin.site.urls, name='admin'),
                  path('__debug__/', include(debug_toolbar.urls)),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'error_handlers.views.handler403'
handler404 = 'error_handlers.views.handler404'
handler500 = 'error_handlers.views.handler500'

softserve_demo1_books/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from book.views import index
from user.api import GetToken, RetrieveUser

urlpatterns = [
                  path('', index),
                  path('book/',
                       include(('book.urls', 'book'), namespace='book')),
                  path('accounts/',
                       include(('user.urls', 'user'), namespace='user')),
                  path('comment/', include(('comment.urls', 'comment'),
                                           namespace='comment')),
                  path('api/author/', include('author.urls')),
                  path('api/book/', include('book.api')),
                  path('api/user/<int:pk>', RetrieveUser.as_view()),
                  path('api/login/', GetToken.as_view()),
                  path('api-login/', include('rest_framework.urls')),
                  path('admin/', admin.site.urls, name='admin'),
                  path('__debug__/', include(debug_toolbar.urls)),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'error_handlers.views.handler403'
handler404 = 'error_handlers.views.handler404'
handler500 = 'error_handlers.views.handler500'

user/urls.py
"""
Urls for User App
"""
from django.urls import path

from user.views import user_login, user_logout, user_register

urlpatterns = [
    path('login/', user_login, name='user_login'),
    path('logout', user_logout, name='user_logout'),
    path('register', user_register, name='user_register'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="description" content=""/>
    <meta name="author" content="Mykola Volosnikov"/>
    <title>
        {% block title %} Books {% endblock %}
    </title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"/>
</head>
<body>
{% block navbar %}
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'book:index' %}">Books</a>
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item"></li>
                    </ul>

                    <form class="d-flex">
                        <div class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                               data-bs-toggle="dropdown">
                                <i class="bi bi-person-fill text-white"></i>
                            </a>
                            <ul class="dropdown-menu">
                                {% if request.user.is_authenticated %}
                                    <li><a class="dropdown-item" href="{% url 'user:user_logout' %}">Logout</a></li>
                                {% else %}
                                    <li><a class="dropdown-item" href="{% url 'user:user_login' %}">Login</a></li>
                                    <li><a class="dropdown-item" href="{% url 'user:user_register' %}">Register</a></li>
                                {% endif %}
                                <li>
                                    <hr class="dropdown-divider"/>
                                </li>
                                <li><a class="dropdown-item" href="{% url 'admin:index' %}" target="_blank">Admin
                                    Site</a></li>
                            </ul>
                        </div>

                        <div class="input-group">
                            <input id="search-field" type="text" class="form-control" placeholder="Search by"/>
                            <div id="search-by-title" class="btn btn-outline-light">Title</div>
                            <div id="search-by-author" class="btn btn-outline-light">Writer</div>
                        </div>
                    </form>
                </div>
            </div>
        </nav>
    </header>
{% endblock %} {% block main %} {% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script>
    $("#search-by-title").click(() => {
        window.location.href = "?title=" + $("#search-field").val();
    });
    $("#search-by-author").click(() => {
        window.location.href = "?author=" + $("#search-field").val();
    });
</script>
</body>
</html>

templates/pagination.html
{% if page_obj.paginator.num_pages != 1 %}
    <div class="d-flex justify-content-center" style="margin-top: 50px;">
        <nav aria-label="...">
            <ul class="pagination pagination-lg" id="pagination_div">

                {% if page_obj.has_previous %}

                    <li class="page-item"><a class="page-link" href="{{ base_url }}&page=1">1</a></li>

                    {% if page_obj.previous_page_number != 1 %}
                        <li class="page-item"><a class="page-link"
                                                 href="{{ base_url }}&page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                        </li>
                    {% endif %}

                {% endif %}

                <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>

                {% if page_obj.has_next %}

                    {% if page_obj.next_page_number != page_obj.paginator.num_pages %}
                        <li class="page-item"><a class="page-link"
                                                 href="{{ base_url }}&page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                        </li>
                    {% endif %}

                    <li class="page-item"><a class="page-link"
                                             href="{{ base_url }}&page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                    </li>

                {% endif %}

            </ul>

        </nav>
    </div>
{% endif %}