book/urls.py
"""
Url Patterns for Book App
"""
from django.urls import path

from book import views

urlpatterns = [
    path('', views.BooksListView.as_view(),
         name='index'),
    path('<int:pk>', views.BookDetailView.as_view(),
         name='book-details'),
    path('<int:pk>/delete', views.BookDeleteView.as_view(),
         name='book-delete'),
    path('<int:pk>/update', views.BookUpdateView.as_view(),
         name='book-update')
]

comment/urls.py
"""
Urls for Comment App
"""
from django.urls import path
from comment import views

urlpatterns = [
    path('<int:pk>/review/add', views.ReviewCreateView.as_view(), name='review-add'),
    path('review/<int:pk>', views.ReviewDetailView.as_view(), name='review-details'),
    path('review/<int:pk>/update', views.ReviewUpdateView.as_view(), name='review-update'),
    path('review/<int:pk>/delete', views.ReviewDeleteView.as_view(), name='review-delete'),
    path('review/<int:pk>/comment/add/<reply_to>', views.CommentCreateView.as_view(), name='comment-add'),
    path('<int:pk>/update', views.CommentUpdateView.as_view(), name='comment-update'),
    path('<int:pk>/delete', views.CommentDeleteView.as_view(), name='comment-delete'),
]

django_books/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from book.views import index
from user.api import GetToken, RetrieveUser

urlpatterns = [
                  path('', index),
                  path('book/',
                       include(('book.urls', 'book'), namespace='book')),
                  path('accounts/',
                       include(('user.urls', 'user'), namespace='user')),
                  path('comment/', include(('comment.urls', 'comment'),
                                           namespace='comment')),
                  path('api/author/', include('author.urls')),
                  path('api/book/', include('book.api')),
                  path('api/user/<int:pk>', RetrieveUser.as_view()),
                  path('api/login/', GetToken.as_view()),
                  path('api-login/', include('rest_framework.urls')),
                  path('admin/', admin.site.urls, name='admin'),
                  path('__debug__/', include(debug_toolbar.urls)),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'error_handlers.views.handler403'
handler404 = 'error_handlers.views.handler404'
handler500 = 'error_handlers.views.handler500'

softserve_demo1_books/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from book.views import index
from user.api import GetToken, RetrieveUser

urlpatterns = [
                  path('', index),
                  path('book/',
                       include(('book.urls', 'book'), namespace='book')),
                  path('accounts/',
                       include(('user.urls', 'user'), namespace='user')),
                  path('comment/', include(('comment.urls', 'comment'),
                                           namespace='comment')),
                  path('api/author/', include('author.urls')),
                  path('api/book/', include('book.api')),
                  path('api/user/<int:pk>', RetrieveUser.as_view()),
                  path('api/login/', GetToken.as_view()),
                  path('api-login/', include('rest_framework.urls')),
                  path('admin/', admin.site.urls, name='admin'),
                  path('__debug__/', include(debug_toolbar.urls)),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'error_handlers.views.handler403'
handler404 = 'error_handlers.views.handler404'
handler500 = 'error_handlers.views.handler500'

book/models.py
from datetime import date

from django.db import models
from django.db.models import QuerySet


class Book(models.Model):
    """
    Book Model
    """
    title = models.CharField(max_length=256)
    rating = models.FloatField()
    publication_year = models.IntegerField(default=date.today().year)
    cover_img = models.ImageField(upload_to='book_covers',
                                  default='book_covers/default.png')
    description = models.TextField()

    authors = models.ManyToManyField('author.Author',
                                     blank=True,
                                     related_name='books')

    class Meta:
        ordering = ['-rating']  # Sort Books by their descending rating

    def __str__(self) -> str:
        return self.title

    @classmethod
    def find_by_title(cls, title: str) -> QuerySet:
        """
        Return book query by matching title
        :param title: str
        :return: QuerySet
        """
        return cls.objects.filter(title__icontains=title).prefetch_related(
            'authors')

    @classmethod
    def find_by_author(cls, name: str) -> QuerySet:
        """
        Return book query by matching author
        :param name: str
        :return: QuerySet
        """
        return cls.objects.filter(
            authors__name__contains=name).prefetch_related('authors')

book/forms.py
from django import forms

from book.models import Book


class BookForm(forms.ModelForm):
    """
    Django Form for Book Model used when creating or updating Book objects
    """

    class Meta:
        model = Book
        fields = ('title', 'rating', 'publication_year',
                  'cover_img', 'description',)

book/views.py
"""
Views for Book App
"""
from django.db.models import QuerySet
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import (ListView, DetailView,
                                  DeleteView, UpdateView)

from book.forms import BookForm
from book.models import Book
from comment.models import Review
from utils.user_utils import (ModeratorRequiredMixin,
                              current_user_is_moderator)


def index(request):
    """
    Redirect User from / to /book,
    which is app index page
    """
    return redirect(reverse_lazy('book:index'))


class BooksListView(ListView):
    """
    Display all books
    """
    paginate_by = 12
    model = Book
    context_object_name = 'books'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._title = None
        self._author = None

    def setup(self, request, *args, **kwargs):
        """
        Save URL Parameters to Object
        """
        self._title = request.GET.get('title')
        self._author = request.GET.get('author')
        return super().setup(request, *args, **kwargs)

    def get_queryset(self) -> QuerySet:
        """
        Filter queryset by title or author when url parameter is provided,
        otherwise, return default query
        :return: QuerySet
        """
        if self._title:
            return Book.find_by_title(self._title)
        elif self._author:
            return Book.find_by_author(self._author)
        return super().get_queryset().prefetch_related('authors')

    def get_context_data(self, *, object_list=None, **kwargs):
        """
        Insert title and author parameters into template context
        """
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['title'] = self._title or ''
        context['author'] = self._author or ''
        return context


class BookDetailView(DetailView):
    """
    Details of a single Book
    """
    paginate_by = 12
    model = Book
    context_object_name = 'book'

    def get_context_data(self, **kwargs):
        """
        Insert page number and reviews into template context
        """
        context = super().get_context_data(**kwargs)
        page = self.request.GET.get('page') or 1
        context['reviews'], context['page_obj'] = Review.get_book_reviews(
            pk=self.object.pk,
            page=page,
            paginate_by=self.paginate_by)
        context['current_user_is_moderator'] = current_user_is_moderator(
            self.request)
        return context


class BookDeleteView(ModeratorRequiredMixin, DeleteView):
    """
    Delete Book View. Only available to moderator or superuser
    """
    model = Book
    success_url = reverse_lazy('book:index')


class BookUpdateView(ModeratorRequiredMixin, UpdateView):
    """
    Update Book View. Only available to moderator or superuser
    """
    model = Book
    form_class = BookForm
    context_object_name = 'book'

    def get_success_url(self):
        """
        Return User to Book Details Page
        """
        return reverse_lazy('book:book-details',
                            kwargs={'pk': self.kwargs.get('pk')})

book/templates/book/book_detail.html
{% extends 'base.html' %} {% block main %}

<main>
    <div class="album py-5">
        <div class="container">
            <div class="jumbotron">
                <img id="cover" class="p-4" src="{{ book.cover_img.url|default:'book_covers/default.png' }}" alt="" />
                <h3 id="name">{{ book.title }}</h3>
                <h5 id="author">
                    by {% for author in book.authors.prefetch_related %}
                    <a href="{% url 'book:index' %}?author={{ author }}" style="text-decoration: none; color: gray;">{{ author }}</a>
                    {% endfor %}
                </h5>
                <h5 id="pub_year">Published {{ book.publication_year }}</h5>
                <h5 id="rating">Rating {{ book.rating }}</h5>
                <div id="description">
                    {{ book.description|safe }}
                </div>
                <br />
                <!-- Control Buttons -->
                {% if current_user_is_moderator %}
                <h5>Moderator Buttons</h5>
                <a class="btn btn-secondary edit-button" href="{% url 'book:book-update' pk=book.pk %}">Edit</a>
                <button class="btn btn-danger delete-button" data-bs-toggle="modal" data-bs-target="#deleteBookModal">Delete</button>
                {% endif %}
            </div>
        </div>
    </div>

    <div id="reviews" class="container">
        <h3>Reviews</h3>

        {% if not reviews %}
        <p>No Reviews yet.</p>
        {% else %}
        <div class="row row-cols-3 g-3">
            {% for review in reviews %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h5 class="card-title"><a href="{% url 'comment:review-details' pk=review.pk %}">{{ review.title }}</a></h5>
                        <p>
                            {{ review.intro|safe }}
                        </p>
                        <h6 class="card-subtitle mb-2 text-muted">by {{ review.reviewer }}</h6>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %} {% if request.user.is_authenticated %}
        <div class="m-4">
            <a href="{% url 'comment:review-add' pk=book.pk %}" class="btn btn-primary">Add Review</a>
        </div>
        {% endif %}
    </div>

    {% block modals %}
    <div class="modal fade" id="deleteBookModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Delete Book?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this book and everything associated with it?
                </div>
                <div class="modal-footer">
                    <form action="{% url 'book:book-delete' pk=book.pk %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
</main>
{% endblock %}

book/templates/book/book_form.html
{% extends 'base.html' %}

{% block main %}
    <div class="jumbotron" style="width: 70%; margin: 50px auto;">
        <form action="{% url 'book:book-update' pk=book.pk %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary" type="submit">Update</button>
        </form>
    </div>
{% endblock %}

book/templates/book/book_list.html
{% extends 'base.html' %} {% block main %}
<main>
    <div class="album py-5 bg-light">
        <div class="container">
            {% if books %}
            <div id="employees_list" class="row row-cols-4 g-3">
                {% for book in books %}
                <div class="col">
                    <div class="card shadow-sm">
                        <img src="{{ book.cover_img.url|default:'book_covers/default.png' }}" class="card-img-top" alt="..." />
                        <div class="card-body">
                            <h5 class="card-title"><a href="{% url 'book:book-details' pk=book.pk %}">{{ book.title }}</a></h5>
                            <h6 class="card-subtitle mb-2 text-muted">
                                by {% for author in book.authors.all %}
                                <a href="{% url 'book:index' %}?author={{ author }}" class="no-style-link">{{ author }}</a>
                                {% endfor %}
                            </h6>
                            <h6 class="card-subtitle mb-2 text-muted">Published {{ book.pub_year }}</h6>
                            <h6 class="card-subtitle mb-2 text-muted">Rating {{ book.rating }}</h6>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% block pagination %} {% with '?title='|add:title|add:'&author='|add:author as base_url %} {% include 'pagination.html' %} {% endwith %} {% endblock %} {% else %}
            <div class="jumbotron">
                <h3>No matching Books found :(</h3>
            </div>
            {% endif %}
        </div>
    </div>
</main>
{% endblock %}